### ISSUE TITLE
Would it be possible for items WITHOUT a thumb image to show an icon based on “Type” ( audio, video, text, html) (right now HTML do not have any icon)

### ISSUE THREAD

**Issue by orangewolf** [notch8/atla_digital_library#17]
https://github.com/scientist-softserv/atla_digitial_library/issues/202 is a duplicate of this issue

Completing the work on 202 should also fix the issues listed in this ticket. 

# Testing Instruction & Acceptance Criteria
- See 202

**Comment by DiemBTran** [comment]
Christy Feb 2019

---
This will be relevant for Princeton's collection where the item is audio or video and we are not harvesting those files like this collection http://34.218.236.99/collections/7m01bm932?locale=en

**Comment by DiemBTran** [comment]
Christy March 2019

---


![Image](https://user-images.githubusercontent.com/29311858/202011747-f0588ac7-0a60-48c7-8dfc-abb4e5cb4e29.png)

**Comment by DiemBTran** [comment]
Crystal Oct 2022: (updated by Christy)

---

Brooklyn College Library  Sermons collection [linked from the home page](https://dl.atla.com/collections/sermons-of-the-reverend-dr-william-augustus-jones-jr) should have the image that was applied on import - CSV import with an image file. 

This has been replaced with the default icon. 

Any collection that has a thumbnail should use that thumbnail, the default icon should only be used when there is no thumbnail being made available

**Comment by DiemBTran** [comment]
Christy Oct 2022:

---

Just tried importing a new collection on staging using CSV and it has thumbnail urls - these were ignored and the system audio was used instead. That should not be happening.

https://dl-staging.atla.com/collections/american-religious-sounds-project?locale=en[new_Am_Rel_Sounds_of_Atla-metadata_-_Atla-metadata.csv](/uploads/c9e267b7c100b0c768e4cd48453838e5/new_Am_Rel_Sounds_of_Atla-metadata_-_Atla-metadata.csv)

**Comment by summer-cook** [comment]
duplicate: https://github.com/scientist-softserv/atla_digitial_library/issues/202

**Comment by labradford** [comment]
Looks for thumbnail first, then selects icon from filetype. Use CSV import for debugging

**Comment by summer-cook** [comment]
CLOSING as work is being done on duplicate ticket #202

PR Here: #259
