### ISSUE TITLE
institutions page stats incorrect for SWBT

### ISSUE THREAD

**Issue by orangewolf** [notch8/atla_digital_library#187]
![Image](https://user-images.githubusercontent.com/29311858/202043853-044aee2c-b064-43e1-874b-c3262f6dbda9.png)

the stats page shows 1 item but you can see here https://dl.atla.com/collections/southwestern-baptist-theological-seminary-libraries

There are 21 collecitons with lots of items in them

ALSO weird - there is a random item added to this collection by itself - see bottom of that page linked above

**Comment by DiemBTran** [comment]
Crystal Oct 2022

---

Re-run home page script for updating collection amounts.  Confirm this is working.

**Comment by crisr15** [comment]
Ran update_institutions_page 
It increased the count to 3 but is still not correct.  Will be looking into if the other institutions are correct or if this is an isolated incident with SWBT.

**Comment by crisr15** [comment]
Additionally, there are 3 works that are added to the institution page directly that should not be attached to the institution.  There use to be 1 so the script seems to be pulling from items directly on the institution instead of through the collections.

**Comment by crisr15** [comment]
Additional works removed from SWBT collection.  Please rerun update_institutions_page script.

**Comment by crisr15** [comment]
Re-ran task atla:update_institutions_page and counts are now correct.  Task counts works if there are works, and if no works then counts number of works in attached collection.
