### ISSUE TITLE
Can't delete or edit works

### ISSUE THREAD

**Issue by orangewolf** [notch8/atla_digital_library#191]
# Summary

This collection (William Wilberforce Papers, 1782-1837 and undated) was imported via CSV. The thumbnail URLs changed so when the import was updated they went missing. I tried running an update with the new correct thumb URLs and it duplicated all the works. I deleted the duplicates that imported with thumbs and am now trying to delete the original works that have missing thumbs so that I can then run a new CSV import. 

The works will not delete at all and you can't even edit them. It takes you to an error page instead. I tried from the individual work pages as well as the dashboard 

Collection is here: https://dl.atla.com/collections/william-wilberforce-papers-1782-1837-and-undated?locale=en

the error message is "The page you were looking for doesn't exist.
You may have mistyped the address or the page may have moved."
----------

I then tried deleting these Works (link below) because they appear to be duplicates set to private - the same issue, they will not delete -
https://dl.atla.com/dashboard/my/works/page/6?f%5Bvisibility_ssi%5D%5B%5D=restricted&locale=en&per_page=100&route_set=%23%3CActionDispatch%3A%3ARouting%3A%3ARoutesProxy%3A0x00007fad0b650468%3E

They are all from the Evangelical Beacon collection https://dl.atla.com/collections/evangelical-beacon?locale=en. But I think are duplicates because the public collection is complete

The error message is "We're sorry, but something went wrong.
If you are the application owner check the logs for more information."

**WEIRDLY** - i seem to be able to delete a single work from this randomly. Like i can come in and delete one but then no more and have to wait a while before it lets me delete another one.
UPDATE: i can delete 1 work at a time, it still gives the something went wrong error but when i go back and refresh the work is gone. This does not work for multiple items at once and does not work for the other collection mentioned above

**Comment by ckarpinski** [comment]
testing

**Comment by crisr15** [comment]
I believe this relates to this error: https://sentry.io/organizations/scientist-inc/issues/3604263329/?project=6745022&referrer=project-issue-stream

**Comment by crisr15** [comment]
Sudo code that needs changes (code from destroy method)
title = curation_concern.to_s
        env = Actors::Environment.new(curation_concern, current_ability, {})
        return unless actor.destroy(env)
        Hyrax.config.callback.run(:after_destroy, curation_concern.id, current_user, warn: false)

**Comment by crisr15** [comment]
#217 was created to handle the initial part of this ticket.  

Private works with Evangelical Beacon in the title need to be deleted.

**Comment by crisr15** [comment]
Private works had errors and were incomplete.  They were duplicate or damages records and so were deleted as they could not be edited or deleted.
