### ISSUE TITLE
Remove 2 Princeton collections

### ISSUE THREAD

**Issue by ckarpinski** [notch8/atla_digital_library#211]
I need the works in the collection Princeton Theological Seminary Media Archive removed from the digital library https://dl.atla.com/collections/princeton-theological-seminary-media-archive

and also this one https://dl.atla.com/collections/princeton-theological-seminary-journals?locale=en

I can only delete 50 items at a time because of the known issue of text overlapping the select all when showing 100 works in the dashboard. But probably even 100 at a time would be to slow for this.

**Comment by labradford** [comment]
works in both collections have been deleted
