### ISSUE TITLE
Delete William Wilberforce Papers Collection Works

### ISSUE THREAD

**Issue by crisr15** [notch8/atla_digital_library#217]
# Summary

When trying to edit or delete works from the William Wilberforce papers, 1782 - 1837 and undated collection you get an error about the item not being in active fedora.  We want to delete all of these so they can be reloaded.  

# Acceptance Criteria
Delete all works from “William Wilberforce Papers, 1782 -1837 and undated”
https://sentry.io/organizations/scientist-inc/issues/3740175094/?project=6745022&referrer=project-issue-stream

# Notes: 
https://playbook-staging.notch8.com/en/samvera/how-to-delete-a-solr-object

**Comment by crisr15** [comment]
Confirmed command from playbook article will remove the items.

**Comment by labradford** [comment]
https://dl.atla.com/collections/william-wilberforce-papers-1782-1837-and-undated?locale=en
All of the works in this collection have been deleted from Solr

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screen recording.

tested on:
- https://dl.atla.com/collections/william-wilberforce-papers-1782-1837-and-undated?locale=en
- https://dl.atla.com/dashboard/collections/william-wilberforce-papers-1782-1837-and-undated?locale=en

<details><summary>This collection is now empty</summary>

https://user-images.githubusercontent.com/29311858/208557205-f1728273-7b83-4785-a120-beed24c63849.mp4</details>
