### ISSUE TITLE
Meadville 2 collections with images not showing public

### ISSUE THREAD

**Issue by crisr15** [notch8/atla_digital_library#218]
# Summary

Some collections have come in where the thumbnails are being set to private.  They can be seen when an admin logs in, but not when a non logged in users looks at them.  All thumbnails should show as public. 

Collections:
Unitarian Universalist Women’s Federation Records
https://dl.atla.com/collections/uuwf-records?locale=en
Unitarian Universalist Women and Religion Records
https://dl.atla.com/collections/uuwr-records?locale=en

**Comment by ckarpinski** [comment]
This is not fixed

**Comment by labradford** [comment]
Both collections have been updated
