### ISSUE TITLE
Mochi appearing as language when it should not be

### ISSUE THREAD

**Issue by crisr15** [notch8/atla_digital_library#219]
# Summary

I imported a collection that has “Old English (ca. 450-1100)” in the dc:language and the records come through with English and Mochi??? as a language. Can anyone see why Mochi is showing up? 

this is the collection: https://dl.atla.com/collections/medieval-manuscript-variants-in-aelfric-of-eynsham-s-catholic-homilies?locale=en

Importer: https://dl.atla.com/importers/323?locale=en

The atla_matcher takes the def parse_language method and overrides it to add:
Removing all . periods and split on " " and put all the values into an array, then removes the word and , and filters them through the list you linked.

**Comment by ckarpinski** [comment]
I think we fixed the collection that had this issue and only left the ticket open to see why it happened but we dont need this done.
