### ISSUE TITLE
some missing thumbs CSV import (Duke William Wilbeforce)

### ISSUE THREAD

**Issue by ckarpinski** [notch8/atla_digital_library#222]
Imported this collection by CSV and there are works missing their thumbnail images 
https://dl.atla.com/collections/william-wilberforce-papers-1782-1837-and-undated

CSV is here https://docs.google.com/spreadsheets/d/1zAyKQvQzPOGrawocKM3iTegMKi9mNboVEq9FMIF6e1U/edit#gid=50593550

There are URLs to the thumbs - i spot checked a couple missing ones and they have URLS that go to images.

# testing instructions
### if there isn't a work missing a thumbnail and you just need to test this feature, complete the steps below.
1. find a work that has a thumbnail
2. remove the thumbnail
    ``` sh
    # bash into the container (docker compose exec web bash)
    # get into the rails console (rails c)
    w = Work.find <id of the work you found above> # e.g. w = Work.find '12345'
    w.thumbnail = nil
    w.save
    ```
3. run the rake task to bring the thumbnail back
    ``` sh
    # exit the rails console by typing "exit"
    rake atla:update_thumbnail_path_for_one_work[id of the work you found above]
    # e.g. rake atla:update_thumbnail_path_for_one_work[12345]
    ```

### if there's already one or more works missing thumbnails, run one of the rake tasks below depending on the situation
``` sh
# fix the thumbnail path for a given work id
rake atla:update_thumbnail_path_for_one_work[work_id] # e.g. rake atla:update_thumbnail_path_for_one_work[12345]

# fix the thumbnail paths for the given bulkrax importer id
rake atla:update_thumbnail_paths_per_bulkrax_importer[bulkrax_id] # e.g. rake atla:update_thumbnail_paths_per_bulkrax_importer[1]

# fix the thumbnail paths for all works in the database
rake atla:update_all_thumbnail_paths
```

**Comment by crisr15** [comment]
Add instructions on how Christy can resolve this in the future, if possible.

**Comment by ckarpinski** [comment]
@crisr15 This is on Kevin's list as next teir support - does that mean to get instructions on how to resolve it or doees that mean you all resolving it or both?

Should i just be manually adding images to the works that they are missing from? The urls were correct.

**Comment by alishaevn** [comment]
paired on this with @sephirothkod today.

looking at the solr document for https://dl.atla.com/concern/works/sj139j45m (missing the thumbnail), the `thumbnail_path_ss` value points at a string in the "assets" path. whereas, the solr document for https://dl.atla.com/concern/works/gh93hf179 (has a thumbnail) has a `thumbnail_path_ss` value that points towards "downloads". we believe that's the issue.

it seems like somewhere during the process of creating the work in hyrax, a race condition or something happens and the thumbnail isn't set properly. I'll work on a rake task tomorrow to try and fix the problem with the broken thumbnails in this repo.

<details>
<summary>"sj139j45m" solr doc</summary>

```sh
 @_source=
  {"system_create_dtsi"=>"2023-01-03T22:14:41Z",
   "system_modified_dtsi"=>"2023-01-03T22:15:20Z",
   "has_model_ssim"=>["Work"],
   "id"=>"sj139j45m",
   "accessControl_ssim"=>["8106bc42-c5a6-43c5-8d2a-40070dd90692"],
   "hasRelatedMediaFragment_ssim"=>["8s45qs24x"],
   "hasRelatedImage_ssim"=>["8s45qs24x"],
   "depositor_ssim"=>["rob@notch8.com"],
   "depositor_tesim"=>["rob@notch8.com"],
   "title_tesim"=>["Correspondence, 1831-1837, 71"],
   "date_uploaded_dtsi"=>"2023-01-03T22:14:41Z",
   "date_modified_dtsi"=>"2023-01-03T22:14:41Z",
   "isPartOf_ssim"=>["admin_set/default"],
   "contributing_institution_tesim"=>["Duke University Libraries"],
   "date_tesim"=>["1831/1837"],
   "format_original_tesim"=>["Correspondence"],
   "types_tesim"=>["Text"],
   "subject_tesim"=>["Wilberforce, William, 1759-1833"],
   "rights_statement_tesim"=>["https://creativecommons.org/publicdomain/mark/1.0"],
   "identifier_tesim"=>["https://idn.duke.edu/ark:/87924/r4w952j42"],
   "ancestor_collection_ids_tesim"=>["ww72bj826", "h989rb20j"],
   "ancestor_relationships_tesim"=>["ww72bj826:h989rb20j"],
   "thumbnail_path_ss"=>"/assets/work-e9cc53840eb6036829765eb10a353810f3c1e4ded4b21be2823c053c8cfb74ea.png",
   "suppressed_bsi"=>false,
   "actionable_workflow_roles_ssim"=>["admin_set/default-default-managing", "admin_set/default-default-approving", "admin_set/default-default-depositing"],
   "workflow_state_name_ssim"=>["deposited"],
   "member_ids_ssim"=>["8s45qs24x"],
   "member_of_collections_ssim"=>["William Wilberforce Papers, 1782-1837 and undated"],
   "member_of_collection_ids_ssim"=>["h989rb20j"],
   "file_set_ids_ssim"=>["8s45qs24x"],
   "visibility_ssi"=>"open",
   "admin_set_tesim"=>["Default Admin Set"],
   "human_readable_type_tesim"=>["Work"],
   "read_access_group_ssim"=>["public"],
   "edit_access_group_ssim"=>["admin"],
   "edit_access_person_ssim"=>["rob@notch8.com"],
   "nesting_collection__ancestors_ssim"=>["ww72bj826", "ww72bj826/h989rb20j"],          
   "nesting_collection__parent_ids_ssim"=>["h989rb20j"],
   "nesting_collection__pathnames_ssim"=>["ww72bj826/h989rb20j/sj139j45m"],
   "nesting_collection__deepest_nested_depth_isi"=>3,
   "_version_"=>1754041467645460480,
   "timestamp"=>"2023-01-03T22:18:17.605Z"}
```
</details>


<details>
<summary>"gh93hf179" solr doc</summary>

```sh
 @_source=
  {"system_create_dtsi"=>"2023-01-03T22:14:59Z",
   "system_modified_dtsi"=>"2023-01-03T22:15:54Z",
   "has_model_ssim"=>["Work"],
   "id"=>"gh93hf179",
   "accessControl_ssim"=>["3f425af3-3063-4b9d-8e5f-7b4dac4f2e32"],
   "hasRelatedMediaFragment_ssim"=>["xd07h967j"],
   "hasRelatedImage_ssim"=>["xd07h967j"],
   "depositor_ssim"=>["rob@notch8.com"],
   "depositor_tesim"=>["rob@notch8.com"],
   "title_tesim"=>["Correspondence, 1831-1837, 72"],
   "date_uploaded_dtsi"=>"2023-01-03T22:14:58Z",
   "date_modified_dtsi"=>"2023-01-03T22:14:58Z",
   "isPartOf_ssim"=>["admin_set/default"],
   "contributing_institution_tesim"=>["Duke University Libraries"],
   "date_tesim"=>["1831/1837"],
   "format_original_tesim"=>["Correspondence"],
   "types_tesim"=>["Text"],
   "subject_tesim"=>["Wilberforce, William, 1759-1833"],
   "rights_statement_tesim"=>["https://creativecommons.org/publicdomain/mark/1.0"],
   "identifier_tesim"=>["https://idn.duke.edu/ark:/87924/r4b56g169"],
   "ancestor_collection_ids_tesim"=>["ww72bj826", "h989rb20j"],
   "ancestor_relationships_tesim"=>["ww72bj826:h989rb20j"],
   "thumbnail_path_ss"=>"/downloads/xd07h967j?file=thumbnail",
   "suppressed_bsi"=>false,
   "actionable_workflow_roles_ssim"=>["admin_set/default-default-managing", "admin_set/default-default-approving", "admin_set/default-default-depositing"],
   "workflow_state_name_ssim"=>["deposited"],
   "member_ids_ssim"=>["xd07h967j"],
   "member_of_collections_ssim"=>["William Wilberforce Papers, 1782-1837 and undated"],
   "member_of_collection_ids_ssim"=>["h989rb20j"],
   "file_set_ids_ssim"=>["xd07h967j"],
   "visibility_ssi"=>"open",
   "admin_set_tesim"=>["Default Admin Set"],
   "human_readable_type_tesim"=>["Work"],
   "read_access_group_ssim"=>["public"],
   "edit_access_group_ssim"=>["admin"],
   "edit_access_person_ssim"=>["rob@notch8.com"],
   "nesting_collection__ancestors_ssim"=>["ww72bj826", "ww72bj826/h989rb20j"],
   "nesting_collection__parent_ids_ssim"=>["h989rb20j"],
   "nesting_collection__pathnames_ssim"=>["ww72bj826/h989rb20j/gh93hf179"],
   "nesting_collection__deepest_nested_depth_isi"=>3,
   "_version_"=>1754041471453888512,
   "timestamp"=>"2023-01-03T22:18:21.236Z"}
```
</details>

**Comment by alishaevn** [comment]
# testing instructions
### if there isn't a work missing a thumbnail and you just need to test this feature, complete the steps below.
1. find a work that has a thumbnail
2. remove the thumbnail
    ``` sh
    # bash into the container (docker compose exec web bash)
    # get into the rails console (rails c)
    w = Work.find <id of the work you found above> # e.g. w = Work.find '12345'
    w.thumbnail = nil
    w.save
    ```
3. run the rake task to bring the thumbnail back
    ``` sh
    # exit the rails console by typing "exit"
    rake atla:update_thumbnail_path_for_one_work[id of the work you found above]
    # e.g. rake atla:update_thumbnail_path_for_one_work[12345]
    ```

### if there's already one or more works missing thumbnails, run one of the rake tasks below depending on the situation
``` sh
# fix the thumbnail path for a given work id
rake atla:update_thumbnail_path_for_one_work[work_id] # e.g. rake atla:update_thumbnail_path_for_one_work[12345]

# fix the thumbnail paths for the given bulkrax importer id
rake atla:update_thumbnail_paths_per_bulkrax_importer[bulkrax_id] # e.g. rake atla:update_thumbnail_paths_per_bulkrax_importer[1]

# fix the thumbnail paths for all works in the database
rake atla:update_all_thumbnail_paths
```

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshots.

Thanks for your excellent testing instructions, Alisha!

tested on:
- work whose thumbnail I removed and added back: https://dl-staging.atla.com/concern/works/kd17cs934?locale=en
- checked the `Works` dashboard page to see that thumbnails were removed or added: https://dl-staging.atla.com/dashboard/my/works?locale=en

<details><summary>I chose a work with a thumbnail, removed its thumbnail within the console, and used the rake task to bring its thumbnail back</summary>

![Works - Atla Digital Library 2023-04-17 at 2 56 27 PM](https://user-images.githubusercontent.com/29311858/232620795-832d497b-2691-49bf-a0ce-3dbce2fb3c62.jpg)
![Works - Atla Digital Library 2023-04-17 at 2 56 36 PM](https://user-images.githubusercontent.com/29311858/232620805-8f589249-6218-47bc-86a0-fcaf59cff97a.jpg)
![Works - Atla Digital Library 2023-04-17 at 2 56 47 PM](https://user-images.githubusercontent.com/29311858/232620813-66c66934-1750-4f99-a4d8-e0f789779658.jpg)
</details>

<details><summary>QA Note: The scope of the ticket is to be able to run rake tasks to bring back a work's thumbnail, not "how to remove a thumbnail from a work" (that was just the prework necessary to prep for the actual QA test). But I wanted to leave this QA note for posterity. After removing a work's thumbnail, the thumbnail no longer shows in the Dashboard > Works page (correct). However, I can still see the work as a thumbnail (I think?) on the work show page. This may not actually be a thumbnail, though, since ATLA has some Hyrax customizations under the hood.</summary>

![Test Deploy - Atla Digital Library 2023-04-17 at 3 01 35 PM](https://user-images.githubusercontent.com/29311858/232623205-a0534719-6592-4aa3-9a39-30906b624920.jpg)
</details>

**Comment by alishaevn** [comment]
> After removing a work's thumbnail, the thumbnail no longer shows in the Dashboard > Works page (correct). However, I can still see the work as a thumbnail (I think?) on the work show page. This may not actually be a thumbnail, though, since ATLA has some Hyrax customizations under the hood.

thanks for being thorough @DiemBTran. you are correct that although the image on the work show page is small, it is not actually a thumbnail. 🙂  being able to see it even when the thumbnail is missing, is expected.

**Comment by alishaevn** [comment]
closing this issue. the next steps will be completed on #281.
