### ISSUE TITLE
Bulkrax support for images to show in the IIIF viewer

### ISSUE THREAD

**Issue by crisr15** [notch8/atla_digital_library#227]
# Summary

Bulkrax should support the ability to have files show in the viewer on import.  Christy needs to know how to set this for a work or importer.  

This was perviosly working in ATLA, and ATLA has a setting at the work level that allows a admin to click a button that it should show in the UV.  Alisha did work to make this also something that could be set on import by adding a column.  We need to look at history on the project and on testing sheets to find what had to happen on an import to make the file show in UV, test this, fix if necessary, and document it for Christy.  

# Acceptance Criteria

- [x] Research what solution was put in place and what should show on teh spreadsheet to have it files show in the UV.  
- [x] A field can be set on import to allow the files to show in the UV
- [x] Documentation is delivered to Christy to show how this feature work. 

# Testing
Create an importer with files and follow instructions to have the file show in the UV once work is uploaded.

**Comment by labradford** [comment]
`has_manifest` is the column header for the CSV file. Set this to `1` to have it show in the UV by default

To set this in the Admin Dashboard, you can edit a work and check the box that says "Use IIIF Viewer"

**Comment by labradford** [comment]
https://user-images.githubusercontent.com/18175797/232885001-3904b99e-71a2-4cc5-9481-38fe14204fd8.mp4

**Comment by crisr15** [comment]
Added this to the Notch8 - Atla Metadata Mapping docs for the CSV Template.

**Comment by alishaevn** [comment]
[has_manifest.zip](https://github.com/scientist-softserv/atla_digital_library/files/11275638/has_manifest.zip)


the above zip file (which is also in https://drive.google.com/drive/u/0/folders/16nD6JbwpHxTHro7irZIMN0pPOGbeqzLG) was successfully uploaded to staging and the IIIF viewer shows by default.


![Image](https://user-images.githubusercontent.com/29032869/233146881-6ba86a02-8c53-4f9b-a145-d557c31fc6a0.png)

**Comment by alishaevn** [comment]
@ckarpinski please use the updated zip file in the google drive for testing this feature.

**Comment by ckarpinski** [comment]
@alishaevn wouldnt it be better for me to make my own test? otherwise i am just recreating what you already tested and know works right?

**Comment by alishaevn** [comment]
@ckarpinski yes, you can create your own csv file or zip as well. just make sure that it includes the `has_manifest` column with a value of `1`.
