### ISSUE TITLE
document requirements for a source identifier

### ISSUE THREAD

**Issue by crisr15** [notch8/atla_digital_library#228]
# Summary 

What are the requirements or limitations in creating a source identifier in bulkrax.  These need to be sent to Christy and should also be on the wiki if they are not already.  

# Acceptance Criteria

- [x] Documentation has been sent for Christy about requirements on the source identifier
- [ ] If this does not yet exist on the bulkrax wiki it is added. 

# Additional Details
This conversation has occurred in slack previously.  If not on the wiki start by searching slack.

**Comment by crisr15** [comment]
A bulkrax identifier or source identifier must be unique for the hyrax app or hyku tenant.  
You can not use your seperator and it is recommended that file naming conventions are followed in that there are no spaces, etc.

**Comment by crisr15** [comment]
Can someone add the above information to this wiki page: https://github.com/samvera-labs/bulkrax/wiki/CSV-Importer#source-identifier

**Comment by aprilrieger** [comment]
I've meshed it all together but do not have the correct permissions:

## Source Identifier

In Bulkrax, a field representing the `source_identifier` must exist and be unique for the hyrax app or hyku tenant. You can not use your seperator and it is recommended that file naming conventions are followed in that there are no spaces, etc. This field will be used for the import identifier of the Work, FileSet or Collection. When the import runs, it checks whether a Work, FileSet or Collection already exists with that identifier, and if so, it updates that existing item. If it does not, then a new item is created.

There are two ways to set the field:

- Use an existing Hyrax field
  ```
  Bulkrax.setup do | config |
    # Use the doi field (note: doi must be available on all works and collections).
    config.field_mappings['Bulkrax::CsvParser'] = {
      'bulkrax_identifier' => { from: ['original_identifier'], source_identifier: true }
    }
  end
  ```

- Allow Bulkrax to create the `source_identifier`
  - If there isn't a field that's available and unique across all Works and Collections, Bulkrax can make a custom field. An example of how this can be changed in the local application as follows:
  ```
    config.fill_in_blank_source_identifiers = ->(obj, index) { "#{Site.instance.account.name}-#{obj.importerexporter.id}-#{index}" }
    config.field_mappings['Bulkrax::CsvParser'] = {
      'bulkrax_identifier' => { from: ['original_identifier'], source_identifier: true }
    }
  ```
  - You will also need to add the following to "app/indexers/shared_indexer" in your local app
  ```
  solr_doc[Solrizer.solr_name('bulkrax_identifier', :facetable)] = object.bulkrax_identifier
  ```

**Comment by aprilrieger** [comment]
[CSV-Importer.md](https://github.com/scientist-softserv/atla_digitial_library/files/10515250/CSV-Importer.md)

**Comment by bkiahstroud** [comment]
Wiki updated [here](https://github.com/samvera-labs/bulkrax/wiki/CSV-Importer/_compare/b2986d8d6bf578e73767aad48aa048dffd444a7d...57ec266f320581eb86ba4cc0bdb1e8ec945e5982)
