### ISSUE TITLE
Push CSV importer bug fix to Atla production

### ISSUE THREAD

**Issue by bkiahstroud** [notch8/atla_digital_library#235]
## Summary

[This CSV importer on production](https://dl.atla.com/importers/326?locale=en) is trying to import a Collection that has a colon (`:`) in the title. This is causing the jobs to infinitely reschedule themselves because the title is splitting on that character. 

Rob has already pushed a fix to the [atla_tmp](https://github.com/samvera-labs/bulkrax/tree/atla_tmp) Bulkrax branch. That fix needs to make it's way to the production site. 

## Acceptance Criteria 

- [ ] The `:` in Collection title bug fix has been pushed to production 

## Implementation Details 

_This is a general order of operations / required steps_

1. `git checkout` the Atla [production](https://github.com/scientist-softserv/atla_digitial_library/tree/production) branch 
2. Spin the app up on that branch locally 
3. `bundle update --conservative bulkrax` to pull in the update on the `atla_tmp` branch 
4. Copy the GitHub actions from the Atla `main` branch into the `production` branch. This will enable us to deploy the branch 
5. Deploy the branch to Atla production 
6. Scale the `worker` pods back up to 3 in r2

**Comment by bkiahstroud** [comment]
The [production](https://github.com/scientist-softserv/atla_digitial_library/compare/production) branch has been prepped. Going to wait until the AM to do the deploy

**Comment by ckarpinski** [comment]
I started this importer again to see if it will import all now. There are 150 items but there should be 181

**Comment by bkiahstroud** [comment]
> I started this importer again to see if it will import all now. There are 150 items but there should be 181

@ckarpinski I think this import run is queued behind the currently-running Princeton import. I don't think you'll see any updates until that importer finishes processing

**Comment by bkiahstroud** [comment]
@ckarpinski it looks like this has finished processing, it is now ready to be verified.

**Comment by crisr15** [comment]
Closing issue as Christy marked Done.
