### ISSUE TITLE
Google analytics no longer in hyrax

### ISSUE THREAD

**Issue by crisr15** [notch8/atla_digital_library#241]
# Summary
Looking at our site home page it looks like there is no google analytics in the page any longer, but it was there at one point. 

slack thread for analytics number: https://assaydepot.slack.com/archives/G031E2NF43T/p1676920097017289?thread_ts=1676918653.565719&cid=G031E2NF43T

# Acceptance Criteria: 

- [x] Google analytics is tracking for hyrax again.

**Comment by ckarpinski** [comment]
This is working.
