### ISSUE TITLE
Bulkrax::OaiIaParser import error after bulkrax upgrade

### ISSUE THREAD

**Issue by crisr15** [notch8/atla_digital_library#248]
# Summary

After the bulkrax upgrade OAI import has stopped working.  Two different errors have been seen: 

Error: Faraday::TimeoutError - Net::ReadTimeout
https://dl-staging.atla.com/importers/68?locale=en
Parser: Bulkrax::OaiIaParser

Error: NoMethodError - undefined method `system_identifier_field' for Bulkrax:Module
importers: https://dl-staging.atla.com/importers/58?locale=en and https://dl-staging.atla.com/importers/59?locale=en
parser: Bulkrax::OaiIaParser

# Acceptance Criteria

- [ ] no longer seeing the above errors on OAI imports using Bulkrax::OaiIaParser

# Notes
#236 has a comment with different OAI feeds that can be used for testing. 

# Testing Instructions
1. Sign in and go to the /importers page
2. Click the button to create a new importer
3. Use the following applicable info to fill out the importer:

name: `AMBS -  Biblioteca Digital Anabautista`
admin_set_id: `admin_set/default`
limit: `25` <---- set this or you will get ALOT of entries
parser: `OAI - Internet Archive`
base_url: `https://archive.org/services/oai.php`
metadata_prefix: `oai_dc`
set: `collection:bibliotecadigitalanabautista`
collection_title: `AMBS -  Biblioteca Digital Anabautista`
institution_name: `Anabaptist Mennonite Biblical Seminary`
thumbnail_url: `https://archive.org/services/img/<%= identifier.split(':').last %>"}`

4. Ensure the importer says "completed" and works import successfully, report any errors you see with screenshots and behavior description, try to include as much detail as possible so we can pickup where you left off if it gets kicked back :)
5. just test that the import for the OAI Internet Archive Parser succeeds for now. you will notice that at this point collections & filesets still may not be attaching correctly. This will be taken care of in this ticket #280

**Comment by summer-cook** [comment]
Note: I have seen the `Error: Faraday::TimeoutError - Net::ReadTimeout` as well- usually i need to fix it by restarting the fedora container (`dc restart fcrepo`)

**Comment by summer-cook** [comment]
https://github.com/scientist-softserv/atla_digital_library/pull/275

**Comment by crisr15** [comment]
Ticket for relationships and file sets #279 
And then #280

**Comment by aprilrieger** [comment]
oai_ia feed url: [https://archive.org/services/oai2.php?verb=ListRecords&metadataPrefix=oai_dc&set=collection:bibliotecadigitalanabautista](https://archive.org/services/oai2.php?verb=ListRecords&metadataPrefix=oai_dc&set=collection:bibliotecadigitalanabautista)

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshots.

tested on:
- importer: https://dl-staging.atla.com/importers/77?locale=en

<details><summary>OAI import completed without error within 5 mn🎉 </summary>

![Atla Digital Library 2023-04-24 at 4 19 47 PM (1)](https://user-images.githubusercontent.com/29311858/234136619-1e48f12f-19d1-4cb9-b5f9-fa471f1ff1c9.jpg)
![Atla Digital Library 2023-04-24 at 4 21 01 PM](https://user-images.githubusercontent.com/29311858/234136614-d687c98d-56b1-4aca-8845-fd14ac4eba22.jpg)
![Atla Digital Library 2023-04-24 at 4 22 47 PM](https://user-images.githubusercontent.com/29311858/234136617-c6b05253-2abf-4967-8edb-fe4200832ff3.jpg)
</details>
