### ISSUE TITLE
Bagit export error

### ISSUE THREAD

**Issue by labradford** [notch8/atla_digital_library#262]
Related to https://github.com/scientist-softserv/atla_digital_library/issues/240
```
["error_class", "NoMethodError"], ["error_message", "undefined method `[]' for nil:NilClass"]
/bulkrax/app/models/bulkrax/csv_entry.rb:144 in `block in build_relationship_metadata` method
```

**Comment by crisr15** [comment]
Bagit Export is not a requirement for ATLA digital library at this point.  This ticket is being closed, but would need to be addressed if ever ATLA did need bagit export. 

Ticket is being created to remove bagit as an option from the exporters.
