### ISSUE TITLE
backups for ATLA

### ISSUE THREAD

**Issue by summer-cook** [notch8/atla_digital_library#266]
# Summary
Received this message from Christy in slack on 4/18

![Image](https://user-images.githubusercontent.com/73361970/232540377-f70ee355-9407-4f51-bce5-597ed64cc1f4.png)

She forwarded the email and it says this/should have been received by Rob on 4/17:

![Image](https://user-images.githubusercontent.com/73361970/232540602-44a16634-1093-4c93-bfa5-47cfcc2cd1c3.png)

# Acceptance Criteria
- [ ] backups for atla digital library are no longer failing.

**Comment by crisr15** [comment]
When servers were upgraded we stopped using this backup method.  We will be turning these off, and the current backups are running.

**Comment by summer-cook** [comment]
Client has been notified in the s3-atla slack channel
