### ISSUE TITLE
Remove Bagit option from export

### ISSUE THREAD

**Issue by crisr15** [notch8/atla_digital_library#267]
# Summary

With the upgrade to bulkrax bagit has been included in export options, but is not yet configured or working properly.  We do not want app users to get confused.  Please remove the bagit option from the export dropdown on the exporter page.  

# Acceptance Criteria

- [ ] As an admin, when I go to do an export, I do not have an option to export in the bagit format. 

# Testing Instructions

This ticket should be moved to deploy to production after going through softserv QA.  Client does not need to test.  

1. Go to create an export page.  
2. Look at export format options
3. Confirm there is no bagit option.

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshot. `This ticket should be moved to deploy to production after going through softserv QA. Client does not need to test.`

tested on:
- https://dl-staging.atla.com/exporters/new?locale=en

<details><summary>bagit export format has been removed. </summary>

![Atla Digital Library 2023-04-18 at 11 31 29 AM](https://user-images.githubusercontent.com/29311858/232871187-5e934f11-7a38-41c7-8a62-284f3ed33b77.jpg)
</details>
