### ISSUE TITLE
resolve build pipeline error

### ISSUE THREAD

**Issue by alishaevn** [notch8/atla_digital_library#286]
# Story
as of april 25, 2023 we began seeing [failed builds](https://github.com/scientist-softserv/atla_digital_library/actions/runs/4809489159) in our pipelines. although `main` built successfully on april 21, running `docker compose build --no-cache` on `main` locally today resulted in the same failed build. 

april was able to find [an announcement](https://lists.debian.org/debian-devel-announce/2023/03/msg00006.html) that appears to be the cause of our issues.

# Acceptance Criteria

- [ ] Attempt updating package URL. If this doesn't resolve the issue, make a new ticket for it and close this one (timebox: 1 hr) 

# Screenshots / Video
<details>
<summary>error message</summary>

![image](https://user-images.githubusercontent.com/29032869/234649283-11ec1cf2-9025-462f-9a18-1e1ec14ff655.png)
</details>

<details>
<summary>announcement</summary>

![image](https://user-images.githubusercontent.com/29032869/234648577-a43b19e1-2600-4ad1-b945-eb9ba94a56bb.png)
</details>

# Notes

**Comment by summer-cook** [comment]
time box of 1 hr

**Comment by alishaevn** [comment]
closing this ticket because the [deploy of `main` to staging](https://github.com/scientist-softserv/atla_digital_library/actions/runs/4824179690) succeeded.
