### ISSUE TITLE
Security site report from Jim June 2023

### ISSUE THREAD

**Issue by ckarpinski** [notch8/atla_digital_library#316]
I am sending the June security report in slack - it has things (likely omeka still) that need addressing

**Comment by aprilrieger** [comment]
Now that Omeka is updated and on production, I would love to get a new security scan to see where we are at now, and make actionable items against the updated security scan. @ckarpinski what do you and/or Jim think about this strategy?

**Comment by aprilrieger** [comment]
[2023-06-02 20_51_52_dl.atla.com_11074060_FAIL.pdf](https://github.com/scientist-softserv/atla_digital_library/files/12053112/2023-06-02.20_51_52_dl.atla.com_11074060_FAIL.pdf)

**Comment by aprilrieger** [comment]
@ckarpinski after re-reading the June security scan, I am confident to say those items will be resolved if scanned again.

**Comment by aprilrieger** [comment]
Closing as complete since Omeka was upgraded. We will deal with any updated security scan issues at the next time the scan is run.
