### ISSUE TITLE
K3 certs expire AUG 27 on ATLA servers

### ISSUE THREAD

**Issue by crisr15** [notch8/atla_digital_library#318]
## Summary

Expire on: Aug 27 12:11:35 2023 GMT

The worker nodes will be removed from the node pool.

The sites will go down.

DO NOT delete the nodes. Follow the instructions below to get the new certs regenerated.

[https://www.ibm.com/support/pages/node/6444205](https://www.google.com/url?q=https://www.ibm.com/support/pages/node/6444205&sa=D&source=calendar&ust=1690390806708097&usg=AOvVaw2HRJQhXVpTMWK8aGWJZ8Nz)

## Acceptance Criteria

- [ ] certs have been updated

## Testing Instructions
Not end user testable.  Close once work is complete

**Comment by aprilrieger** [comment]
@orangewolf Do you think the new EKS cluster will be ready before this work will need to get accomplished for the K3 cluster?

**Comment by aprilrieger** [comment]
This is no longer a necessity as we have moved away form the k3 cluster and have an eks k8 cluster instead.
