### ISSUE TITLE
Security scan issues

### ISSUE THREAD

**Issue by ckarpinski** [notch8/atla_digital_library#330]
The most recent security scan shows that there are a number of new problems. I dont see a way to attach the file here so will put it in slack

PDF https://assaydepot.slack.com/archives/C031E2NF43T/p1695054185432439

**Comment by DraxIndustries79** [comment]
[2023-09-14 17_49_11_dl.atla.com_11275315_FAIL.pdf](https://github.com/scientist-softserv/atla_digital_library/files/13813746/2023-09-14.17_49_11_dl.atla.com_11275315_FAIL.pdf)

**Comment by aprilrieger** [comment]
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL-certificate-rotation.html

**Comment by aprilrieger** [comment]
- [x] TLS Version 1.0 Protocol Detection (Score: 8.5)
- [x] TLS Version 1.1 Protocol Detection and Deprecated (Score: 8.5 and 6.1)
- [x] SSL/TLS Protocol Initialization Vector Implementation Information Disclosure Vulnerability (BEAST) (Score: 4.3)
- [x] SSL/TLS Recommended Cipher Suites (Score: 3.9)
- [x] Git Repository Served by Web Server (Score: 5.0)
- [x] Web Application Information Disclosure (Score: 5.0): The application discloses path information in error messages.
- [x] Web Server Transmits Cleartext Credentials (Score: 4.0): Form fields containing passwords are transmitting data in cleartext.
- [x] Script Src Integrity Check (Score: 3.9): External script resources are not using integrity checks.
